// src/components/admin/rich-editor.tsx
'use client';

import { useEffect, useRef, useState } from 'react';

export function RichEditor({ value, onChange }: { value: string; onChange: (html: string) => void }) {
  const ref = useRef<HTMLDivElement>(null);
  const [html, setHtml] = useState(false);
  useEffect(() => { const el = ref.current; if (el && !html && el.innerHTML !== value) el.innerHTML = value; }, [value, html]);
  const emit = () => { if (ref.current) onChange(ref.current.innerHTML); };
  const cmd = (e: React.MouseEvent, command: string, arg?: string) => { e.preventDefault(); document.execCommand(command, false, arg); emit(); };
  const link = (e: React.MouseEvent) => { e.preventDefault(); const url = prompt('Indirizzo del link (https://...)'); if (url) { document.execCommand('createLink', false, url); emit(); } };
  const image = (e: React.MouseEvent) => { e.preventDefault(); const url = prompt('URL immagine'); if (url) { document.execCommand('insertHTML', false, `<figure><img src="${url}" alt="" /><figcaption>Didascalia</figcaption></figure><p></p>`); emit(); } };
  const video = (e: React.MouseEvent) => { e.preventDefault(); const url = prompt('URL video YouTube'); if (!url) return; const m = url.match(/(?:v=|youtu\.be\/|embed\/)([\w-]{11})/); document.execCommand('insertHTML', false, `<iframe src="https://www.youtube.com/embed/${m ? m[1] : url}" allowfullscreen></iframe><p></p>`); emit(); };
  const B = ({ t, children, onMouseDown, active }: { t: string; children: React.ReactNode; onMouseDown: (e: React.MouseEvent) => void; active?: boolean }) => <button type="button" title={t} className={active ? 'active' : undefined} onMouseDown={onMouseDown}>{children}</button>;
  return (
    <div className="rte">
      <div className="rte-toolbar">
        <B t="Grassetto" onMouseDown={(e) => cmd(e, 'bold')}><b>B</b></B><B t="Corsivo" onMouseDown={(e) => cmd(e, 'italic')}><i>I</i></B><B t="Sottolineato" onMouseDown={(e) => cmd(e, 'underline')}><u>U</u></B>
        <span className="sep" />
        <B t="Paragrafo" onMouseDown={(e) => cmd(e, 'formatBlock', 'p')}>¶</B><B t="Titolo H2" onMouseDown={(e) => cmd(e, 'formatBlock', 'h2')}>H2</B><B t="Titolo H3" onMouseDown={(e) => cmd(e, 'formatBlock', 'h3')}>H3</B><B t="Citazione" onMouseDown={(e) => cmd(e, 'formatBlock', 'blockquote')}>❝</B>
        <span className="sep" />
        <B t="Elenco puntato" onMouseDown={(e) => cmd(e, 'insertUnorderedList')}>•≡</B><B t="Elenco numerato" onMouseDown={(e) => cmd(e, 'insertOrderedList')}>1≡</B>
        <span className="sep" />
        <B t="Link" onMouseDown={link}>🔗</B><B t="Immagine da URL" onMouseDown={image}>🖼</B><B t="Video YouTube" onMouseDown={video}>▶</B>
        <span className="sep" />
        <B t="Rimuovi formattazione" onMouseDown={(e) => cmd(e, 'removeFormat')}>Tx</B><B t="Annulla" onMouseDown={(e) => cmd(e, 'undo')}>↶</B><B t="Ripeti" onMouseDown={(e) => cmd(e, 'redo')}>↷</B>
        <span className="sep" />
        <B t="Sorgente HTML" active={html} onMouseDown={(e) => { e.preventDefault(); setHtml((v) => !v); }}>&lt;/&gt;</B>
      </div>
      {html ? (
        <textarea className="textarea" style={{ border: 0, minHeight: 420, fontFamily: 'monospace', fontSize: 13 }} value={value} onChange={(e) => onChange(e.target.value)} />
      ) : (
        <div ref={ref} className="rte-content" contentEditable suppressContentEditableWarning data-placeholder="Scrivi qui il corpo dell'articolo..." onInput={emit}
          onPaste={(e) => { e.preventDefault(); document.execCommand('insertText', false, e.clipboardData.getData('text/plain')); }} />
      )}
    </div>
  );
}

// src/app/features/admin/editor/rich-editor.component.ts
import { AfterViewInit, Component, ElementRef, input, output, signal, viewChild } from '@angular/core';

@Component({
  selector: 'app-rich-editor',
  template: `
    <div class="rte">
      <div class="rte-toolbar">
        <button type="button" title="Grassetto" (mousedown)="cmd($event, 'bold')"><b>B</b></button>
        <button type="button" title="Corsivo" (mousedown)="cmd($event, 'italic')"><i>I</i></button>
        <button type="button" title="Sottolineato" (mousedown)="cmd($event, 'underline')"><u>U</u></button>
        <span class="sep"></span>
        <button type="button" title="Paragrafo" (mousedown)="cmd($event, 'formatBlock', 'p')">¶</button>
        <button type="button" title="Titolo H2" (mousedown)="cmd($event, 'formatBlock', 'h2')">H2</button>
        <button type="button" title="Titolo H3" (mousedown)="cmd($event, 'formatBlock', 'h3')">H3</button>
        <button type="button" title="Citazione" (mousedown)="cmd($event, 'formatBlock', 'blockquote')">❝</button>
        <span class="sep"></span>
        <button type="button" title="Elenco puntato" (mousedown)="cmd($event, 'insertUnorderedList')">•≡</button>
        <button type="button" title="Elenco numerato" (mousedown)="cmd($event, 'insertOrderedList')">1≡</button>
        <span class="sep"></span>
        <button type="button" title="Link" (mousedown)="link($event)">🔗</button>
        <button type="button" title="Immagine da URL" (mousedown)="image($event)">🖼</button>
        <button type="button" title="Video YouTube" (mousedown)="video($event)">▶</button>
        <span class="sep"></span>
        <button type="button" title="Rimuovi formattazione" (mousedown)="cmd($event, 'removeFormat')">Tx</button>
        <button type="button" title="Annulla" (mousedown)="cmd($event, 'undo')">↶</button>
        <button type="button" title="Ripeti" (mousedown)="cmd($event, 'redo')">↷</button>
        <span class="sep"></span>
        <button type="button" [class.active]="html()" title="Sorgente HTML" (mousedown)="toggleHtml($event)">&lt;/&gt;</button>
      </div>
      @if (html()) {
        <textarea class="textarea" style="border:0;min-height:420px;font-family:monospace;font-size:13px" [value]="value()" (input)="fromSource($event)"></textarea>
      } @else {
        <div #editor class="rte-content" contenteditable="true" data-placeholder="Scrivi qui il corpo dell'articolo..." (input)="onInput()" (paste)="onPaste($event)"></div>
      }
    </div>
  `,
})
export class RichEditorComponent implements AfterViewInit {
  readonly value = input<string>('');
  readonly valueChange = output<string>();
  readonly html = signal(false);
  private readonly editor = viewChild<ElementRef<HTMLDivElement>>('editor');

  ngAfterViewInit(): void { this.sync(); }

  private sync(): void {
    const el = this.editor()?.nativeElement;
    if (el && el.innerHTML !== this.value()) el.innerHTML = this.value();
  }
  onInput(): void { this.valueChange.emit(this.editor()!.nativeElement.innerHTML); }
  onPaste(e: ClipboardEvent): void {
    e.preventDefault();
    const text = e.clipboardData?.getData('text/plain') ?? '';
    document.execCommand('insertText', false, text);
  }
  cmd(e: Event, command: string, arg?: string): void {
    e.preventDefault();
    document.execCommand(command, false, arg);
    this.onInput();
  }
  link(e: Event): void {
    e.preventDefault();
    const url = prompt('Indirizzo del link (https://...)');
    if (url) { document.execCommand('createLink', false, url); this.onInput(); }
  }
  image(e: Event): void {
    e.preventDefault();
    const url = prompt('URL immagine');
    if (url) { document.execCommand('insertHTML', false, `<figure><img src="${url}" alt="" /><figcaption>Didascalia</figcaption></figure><p></p>`); this.onInput(); }
  }
  video(e: Event): void {
    e.preventDefault();
    const url = prompt('URL video YouTube');
    if (!url) return;
    const m = url.match(/(?:v=|youtu\.be\/|embed\/)([\w-]{11})/);
    const id = m ? m[1] : url;
    document.execCommand('insertHTML', false, `<iframe src="https://www.youtube.com/embed/${id}" allowfullscreen></iframe><p></p>`);
    this.onInput();
  }
  toggleHtml(e: Event): void {
    e.preventDefault();
    this.html.update((v) => !v);
    setTimeout(() => this.sync());
  }
  fromSource(e: Event): void { this.valueChange.emit((e.target as HTMLTextAreaElement).value); }
}
