// src/app/admin/newsletter/page.tsx
import { redirect } from 'next/navigation';
import { ActionButton } from '@/components/ui/action-button';
import { removeSubscriberAction } from '@/lib/actions';
import { requireUser } from '@/lib/auth';
import { can } from '@/lib/permissions';
import { getSubscribers } from '@/lib/queries';
import { formatDate } from '@/lib/utils';

export default async function NewsletterPage() {
  const me = await requireUser();
  if (!can(me, 'comment.moderate')) redirect('/admin');
  const subs = getSubscribers();
  const csv = 'data:text/csv;charset=utf-8,' + encodeURIComponent('email,data\n' + subs.map((s) => `${s.email},${s.createdAt}`).join('\n'));
  return (
    <>
      <div className="page-title"><div><h1>Newsletter</h1><p>{subs.length} iscritti</p></div><div className="actions"><a className="btn btn-outline" href={csv} download="iscritti.csv">Esporta CSV</a></div></div>
      <div className="table-wrap"><table className="table">
        <thead><tr><th>Email</th><th>Iscritto il</th><th></th></tr></thead>
        <tbody>
          {subs.map((s) => <tr key={s.id}><td><b>{s.email}</b></td><td>{formatDate(s.createdAt)}</td><td><div className="t-actions"><ActionButton className="icon-btn danger" action={removeSubscriberAction.bind(null, s.id)}>🗑</ActionButton></div></td></tr>)}
          {subs.length === 0 && <tr><td colSpan={3}><div className="empty"><h3>Nessun iscritto</h3></div></td></tr>}
        </tbody></table></div>
    </>
  );
}

// src/app/features/admin/settings/newsletter.component.ts
import { Component, inject } from '@angular/core';
import { StoreService } from '../../../core/services/store.service';
import { ItDatePipe } from '../../../core/pipes';

@Component({
  selector: 'app-newsletter',
  imports: [ItDatePipe],
  template: `
    <div class="page-title"><div><h1>Newsletter</h1><p>{{ store.subscribers().length }} iscritti</p></div><div class="actions"><button class="btn btn-outline" (click)="exportCsv()">Esporta CSV</button></div></div>
    <div class="table-wrap"><table class="table">
      <thead><tr><th>Email</th><th>Iscritto il</th><th></th></tr></thead>
      <tbody>
        @for (s of store.subscribers(); track s.id) {
          <tr><td><b>{{ s.email }}</b></td><td>{{ s.createdAt | itDate }}</td><td><div class="t-actions"><button class="icon-btn danger" (click)="store.removeSubscriber(s.id)">🗑</button></div></td></tr>
        } @empty { <tr><td colspan="3"><div class="empty"><h3>Nessun iscritto</h3></div></td></tr> }
      </tbody></table></div>
  `,
})
export class NewsletterComponent {
  readonly store = inject(StoreService);
  exportCsv(): void {
    const csv = 'email,data\n' + this.store.subscribers().map((s) => `${s.email},${s.createdAt}`).join('\n');
    const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); a.download = 'iscritti.csv'; a.click();
  }
}
