// src/app/features/admin/editor/media-picker.component.ts
import { Component, inject, output, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { StoreService } from '../../../core/services/store.service';
import { AuthService } from '../../../core/services/auth.service';
import { MediaItem } from '../../../core/models';

@Component({
  selector: 'app-media-picker',
  imports: [FormsModule],
  template: `
    <div class="modal-backdrop" (click)="close.emit()">
      <div class="modal" (click)="$event.stopPropagation()">
        <div class="modal-head"><h3>Libreria media</h3><button class="icon-btn" (click)="close.emit()">✕</button></div>
        <div class="modal-body">
          <div class="filters">
            <input class="input grow" placeholder="Cerca..." [(ngModel)]="q" />
            <input class="input grow" placeholder="Oppure incolla un URL immagine" [(ngModel)]="url" />
            <button class="btn btn-outline" (click)="useUrl()" [disabled]="!url">Usa URL</button>
            <label class="btn btn-dark">Carica<input type="file" accept="image/*" hidden (change)="upload($event)" /></label>
          </div>
          <div class="media-grid">
            @for (m of items(); track m.id) {
              <div class="media-item" [class.selected]="sel()?.id === m.id" (click)="sel.set(m)" (dblclick)="pick(m)">
                <div class="m-img"><img [src]="m.url" [alt]="m.alt" loading="lazy" /></div><div class="m-name">{{ m.name }}</div>
              </div>
            }
          </div>
        </div>
        <div class="modal-foot">
          <button class="btn btn-ghost" (click)="close.emit()">Annulla</button>
          <button class="btn btn-primary" [disabled]="!sel()" (click)="pick(sel()!)">Seleziona</button>
        </div>
      </div>
    </div>
  `,
})
export class MediaPickerComponent {
  private readonly store = inject(StoreService);
  private readonly auth = inject(AuthService);
  readonly picked = output<MediaItem>();
  readonly close = output<void>();
  readonly sel = signal<MediaItem | null>(null);
  q = ''; url = '';
  items = () => this.store.media().filter((m) => m.type === 'image' && (!this.q || m.name.toLowerCase().includes(this.q.toLowerCase())));
  pick(m: MediaItem): void { this.picked.emit(m); }
  useUrl(): void {
    const m = this.store.addMedia({ name: this.url.split('/').pop() || 'immagine', url: this.url, alt: '', type: 'image', size: 0, uploadedBy: this.auth.user()!.id });
    this.pick(m);
  }
  upload(e: Event): void {
    const file = (e.target as HTMLInputElement).files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => {
      const m = this.store.addMedia({ name: file.name, url: reader.result as string, alt: file.name, type: 'image', size: file.size, uploadedBy: this.auth.user()!.id });
      this.pick(m);
    };
    reader.readAsDataURL(file);
  }
}

// src/components/admin/media-picker.tsx
'use client';

import { useState } from 'react';
import { addMediaAction } from '@/lib/actions';
import { MediaItem } from '@/lib/models';
import { toast } from '@/components/ui/toaster';

export function readFileAsDataUrl(file: File): Promise<string> {
  return new Promise((res, rej) => { const r = new FileReader(); r.onload = () => res(r.result as string); r.onerror = rej; r.readAsDataURL(file); });
}

export function MediaPicker({ media, onPick, onClose }: { media: MediaItem[]; onPick: (m: MediaItem) => void; onClose: () => void }) {
  const [q, setQ] = useState(''); const [url, setUrl] = useState(''); const [sel, setSel] = useState<MediaItem | null>(null); const [busy, setBusy] = useState(false);
  const items = media.filter((m) => m.type === 'image' && (!q || m.name.toLowerCase().includes(q.toLowerCase())));
  const add = async (m: { name: string; url: string; alt: string; size: number }) => {
    setBusy(true);
    const item = await addMediaAction(m);
    setBusy(false);
    if (item) onPick(item); else toast.error('Impossibile aggiungere il file.');
  };
  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="modal" onClick={(e) => e.stopPropagation()}>
        <div className="modal-head"><h3>Libreria media</h3><button className="icon-btn" onClick={onClose}>✕</button></div>
        <div className="modal-body">
          <div className="filters">
            <input className="input grow" placeholder="Cerca..." value={q} onChange={(e) => setQ(e.target.value)} />
            <input className="input grow" placeholder="Oppure incolla un URL immagine" value={url} onChange={(e) => setUrl(e.target.value)} />
            <button className="btn btn-outline" disabled={!url || busy} onClick={() => add({ name: url.split('/').pop() || 'immagine', url, alt: '', size: 0 })}>Usa URL</button>
            <label className="btn btn-dark">Carica<input type="file" accept="image/*" hidden onChange={async (e) => { const f = e.target.files?.[0]; if (!f) return; if (f.size > 2 * 1024 * 1024) { toast.error('Massimo 2 MB nella demo.'); return; } add({ name: f.name, url: await readFileAsDataUrl(f), alt: f.name, size: f.size }); }} /></label>
          </div>
          <div className="media-grid">
            {items.map((m) => (
              <div key={m.id} className={`media-item ${sel?.id === m.id ? 'selected' : ''}`} onClick={() => setSel(m)} onDoubleClick={() => onPick(m)}>
                <div className="m-img"><img src={m.url} alt={m.alt} loading="lazy" /></div><div className="m-name">{m.name}</div>
              </div>
            ))}
          </div>
        </div>
        <div className="modal-foot"><button className="btn btn-ghost" onClick={onClose}>Annulla</button><button className="btn btn-primary" disabled={!sel} onClick={() => sel && onPick(sel)}>Seleziona</button></div>
      </div>
    </div>
  );
}
