// src/app/features/public/shared/article-card.component.ts
import { Component, computed, inject, input } from '@angular/core';
import { RouterLink } from '@angular/router';
import { Article } from '../../../core/models';
import { StoreService } from '../../../core/services/store.service';
import { TimeAgoPipe } from '../../../core/pipes';

export type CardVariant = 'hero' | 'hero-overlay' | 'md' | 'sm' | 'horizontal' | 'compact' | 'number';

@Component({
  selector: 'app-article-card',
  imports: [RouterLink, TimeAgoPipe],
  template: `
    @let a = article();
    @let cat = category();
    <article class="card" [class.card-hero]="variant() === 'hero' || variant() === 'hero-overlay'" [class.overlay]="variant() === 'hero-overlay'"
      [class.card-md]="variant() === 'md'" [class.card-sm]="variant() === 'sm'" [class.card-horizontal]="variant() === 'horizontal'"
      [class.card-compact]="variant() === 'compact'" [class.card-number]="variant() === 'number'">
      @if (variant() === 'number') {
        <span class="num">{{ index() }}</span>
      } @else {
        <a class="card-img" [routerLink]="link()" [attr.aria-label]="a.title">
          <img [src]="a.coverImage" [alt]="a.title" loading="lazy" width="800" height="500" />
          @if (variant() !== 'compact') {
            <span class="card-badges">
              @if (a.format === 'live' && a.liveActive) { <span class="badge badge-live">Diretta</span> }
              @else if (a.breaking) { <span class="badge badge-red">Ultim'ora</span> }
            </span>
            @if (a.format === 'video') { <span class="card-format">▶</span> }
            @else if (a.format === 'gallery') { <span class="card-format">▦</span> }
          }
        </a>
      }
      <div class="card-body">
        @if (showKicker()) {
          <a class="kicker" [routerLink]="['/', cat?.slug]" [style.color]="variant() === 'hero-overlay' ? null : cat?.color">{{ a.kicker || cat?.name }}</a>
        }
        <h3 class="card-title"><a [routerLink]="link()">{{ a.title }}</a></h3>
        @if (showExcerpt()) { <p class="card-excerpt">{{ a.excerpt }}</p> }
        @if (showMeta()) {
          <div class="meta">
            <span>{{ a.publishedAt | timeAgo }}</span>
            @if (a.sponsored) { <span>· <span class="sponsored-label">Contenuto sponsorizzato</span></span> }
          </div>
        }
      </div>
    </article>
  `,
})
export class ArticleCardComponent {
  private readonly store = inject(StoreService);
  readonly article = input.required<Article>();
  readonly variant = input<CardVariant>('md');
  readonly index = input<number>(0);
  readonly showExcerpt = input<boolean>(false);
  readonly showMeta = input<boolean>(true);
  readonly showKicker = input<boolean>(true);
  readonly category = computed(() => this.store.category(this.article().categoryId));
  readonly link = computed(() => ['/', this.category()?.slug ?? 'notizie', this.article().slug]);
}

// src/components/site/article-card.tsx
import Link from 'next/link';
import { Article, ROLE_LABELS } from '@/lib/models';
import { articleUrl, category, user } from '@/lib/queries';
import { relativeDate } from '@/lib/utils';
import { SmartImage } from '@/components/ui/smart-image';

export type CardVariant = 'hero' | 'md' | 'sm' | 'horizontal' | 'horizontal-sm' | 'compact' | 'number' | 'city' | 'opinion' | 'overlay' | 'overlay-sm';
interface Props { article: Article; variant?: CardVariant; index?: number; showExcerpt?: boolean; showMeta?: boolean; showImage?: boolean; priority?: boolean }

export function Kicker({ article: a, className = 'kicker' }: { article: Article; className?: string }) {
  const cat = category(a.categoryId);
  return (
    <span className={className} style={{ color: cat?.kind === 'dossier' ? 'var(--ink)' : undefined }}>
      {cat?.kind === 'dossier' && <span className="badge badge-yellow">Dossier</span>}
      {a.format === 'live' && a.liveActive && <span className="badge badge-live">Diretta</span>}
      {a.breaking && !(a.format === 'live' && a.liveActive) && <span className="badge badge-red">Ultim&apos;ora</span>}
      <Link href={`/${cat?.slug ?? ''}`}>{a.kicker || cat?.name}</Link>
    </span>
  );
}

export function ArticleCard({ article: a, variant = 'md', index = 0, showExcerpt = false, showMeta = false, showImage = true, priority = false }: Props) {
  const cat = category(a.categoryId);
  const link = articleUrl(a);
  const author = user(a.authorId);
  const cls = `card card-${variant}`;

  if (variant === 'city') {
    return (
      <article className={cls}>
        <h3 className="card-title"><Link href={link}><span className="city">{a.kicker || cat?.name}</span>{a.title}</Link></h3>
      </article>
    );
  }
  if (variant === 'number') {
    return (
      <article className={cls}>
        <span className="num">{index}</span>
        <div className="card-body"><Kicker article={a} /><h3 className="card-title"><Link href={link}>{a.title}</Link></h3></div>
      </article>
    );
  }
  if (variant === 'opinion') {
    return (
      <article className={cls}>
        {author && <div className="op-head"><img src={author.avatar} alt={author.name} /><div><Link className="op-name" href={`/autore/${author.id}`}>{author.name}</Link><div className="op-role">{ROLE_LABELS[author.role]}</div></div></div>}
        <h3 className="card-title"><Link href={link}>{a.title}</Link></h3>
        {showExcerpt && <p className="card-excerpt">{a.excerpt}</p>}
      </article>
    );
  }
  if (variant === 'overlay' || variant === 'overlay-sm') {
    return (
      <article className={`card card-overlay ${variant === 'overlay-sm' ? 'card-overlay-sm' : ''}`}>
        <Link className="card-img" href={link} aria-label={a.title}><SmartImage src={a.coverImage} alt={a.title} priority={priority} sizes={variant === 'overlay' ? '(max-width: 768px) 100vw, 800px' : '(max-width: 768px) 100vw, 400px'} />{a.format === 'video' && <span className="card-format">▶</span>}</Link>
        <div className="card-body">
          <Kicker article={a} />
          <h3 className="card-title"><Link href={link}>{a.title}</Link></h3>
          {showExcerpt && variant === 'overlay' && <p className="card-excerpt">{a.excerpt}</p>}
          {showMeta && <div className="meta"><span>{relativeDate(a.publishedAt)}</span></div>}
        </div>
      </article>
    );
  }
  return (
    <article className={cls}>
      {showImage && variant !== 'compact' && (
        <Link className="card-img" href={link} aria-label={a.title}>
          <SmartImage src={a.coverImage} alt={a.title} priority={priority} sizes={variant === 'horizontal-sm' ? '130px' : '(max-width: 768px) 100vw, 600px'} />
          {a.format === 'video' && <span className="card-format">▶</span>}
          {a.format === 'gallery' && <span className="card-format">▦</span>}
        </Link>
      )}
      <div className="card-body">
        <Kicker article={a} />
        <h3 className="card-title"><Link href={link}>{a.title}</Link></h3>
        {showExcerpt && <p className="card-excerpt">{a.excerpt}</p>}
        {showMeta && <div className="meta"><span>{relativeDate(a.publishedAt)}</span>{a.sponsored && <span>· <span className="sponsored-label">Contenuto sponsorizzato</span></span>}</div>}
      </div>
    </article>
  );
}
